package controller.command;

public enum CommandName {
	GET_VEHICLE, REGISTER_VEHICLE, WRONG_REQUEST, ADD_SLOT, FIND_FREE_SLOT, OCCUPY_SLOT, GET_SLOTS_STATISTICS, GET_CURRENT_SLOT_RESERVATION, FREE_SLOT_RESERVATION, EXIT
}
